package world.taqwa.timetables.golden

import java.io.File

/**
 * Writes `shared/src/commonTest/kotlin/world/taqwa/app/prayer/engine/golden/GoldenVectorData.kt`
 * (spec §3.2, ruling R84): [GOLDEN_CASES], computed once here on the JVM through the app's own
 * [world.taqwa.app.prayer.engine.PrayerEngine.dayTimes], encoded a row per place-day
 * ([encodeRow]) and split into chunks of [CHUNK_SIZE] so no single array literal is huge.
 *
 * `[GoldenVectorTest][world.taqwa.app.prayer.engine.golden]` recomputes every row the same way on
 * each target (JVM, Android, iOS) and compares exactly: the point of the test is that they agree.
 *
 * Regenerate after any change to the engine, the registry, or this generator itself
 * (`./gradlew -p tools/timetables generateGoldenVector`), and commit the result; deterministic (the
 * same inputs give the same bytes every time, since [SEEDS] and the date pools hold no randomness).
 *
 *     ./gradlew -p tools/timetables generateGoldenVector [-Pout=<file>]
 */
fun main(args: Array<String>) {
    val outArg = args.indexOf("--out").takeIf { it >= 0 }?.let { args.getOrNull(it + 1) }
    val out = File(outArg ?: DEFAULT_OUT)

    val rows = GOLDEN_CASES.map { case -> encodeRow(case, compute(case)) }
    println("Golden vector: ${rows.size} place-days over ${SEEDS.size} points, writing to ${out.path}")

    out.parentFile?.mkdirs()
    out.writeText(render(rows))
    println("Wrote ${out.length()} bytes.")
}

private const val DEFAULT_OUT = "shared/src/commonTest/kotlin/world/taqwa/app/prayer/engine/golden/GoldenVectorData.kt"
private const val CHUNK_SIZE = 200

private fun render(rows: List<String>): String = buildString {
    appendLine("// Generated by GenerateGoldenVectorKt (tools/timetables); do not edit by hand.")
    appendLine("// Regenerate: ./gradlew -p tools/timetables generateGoldenVector")
    appendLine("package world.taqwa.app.prayer.engine.golden")
    appendLine()
    appendLine("/**")
    appendLine(" * ${rows.size} invented place-days (spec §3.2, ruling R84), each row in the format")
    appendLine(" * `encodeRow` (tools/timetables) documents and `decodeRow` (GoldenVectorTest, this package)")
    appendLine(" * reads back. Split into chunks of at most $CHUNK_SIZE rows so no single array literal is")
    appendLine(" * huge (Kotlin/Native compile time).")
    appendLine(" */")
    val chunks = rows.chunked(CHUNK_SIZE)
    val chunkNames = chunks.indices.map { "CASES_$it" }
    for ((i, chunk) in chunks.withIndex()) {
        appendLine("private val ${chunkNames[i]}: Array<String> = arrayOf(")
        for (row in chunk) {
            append("    \"")
            append(escape(row))
            appendLine("\",")
        }
        appendLine(")")
        appendLine()
    }
    appendLine("/** Every golden-vector row, in the order [GenerateGoldenVectorKt] wrote them. */")
    appendLine("val GOLDEN_VECTOR_ROWS: List<String> = listOf(${chunkNames.joinToString(", ")}).flatMap { it.asList() }")
}

/** Escapes a row for a Kotlin string literal (none of our fields use these characters, but a future
 * one might: an admin-1 name with an accent needs none of this, only `"`, `\` and `$` would). */
private fun escape(row: String): String = row.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$")
