package world.taqwa.timetables.units

import world.taqwa.timetables.gate.Gate
import world.taqwa.timetables.gate.GateManifest
import world.taqwa.timetables.gate.GateRow
import world.taqwa.timetables.gate.OfficialRoots
import java.io.File
import java.util.Locale
import java.util.concurrent.Executors
import kotlin.system.exitProcess

/**
 * Each own-point row's own worst lateness, per event (the review of 10 Oct 2026): the rows of Umm al-Qura's and
 * QMDB's group files (sa-ummalqura.tsv, kz-qmdb.tsv), each unit's own point and the app's city points, which the
 * reach rows' wider limits no longer hold to their own numbers. `CityUnitsTest` holds every such row to its worst
 * here, so a one-minute regression at a city's own point fails even far below its entry's limit (Almaty, Taraz).
 *
 *     ./gradlew -p tools/timetables generateOwnPointWorst
 *
 * Written to `official/own-points-worst.tsv`: minutes and the rows' paths and points only, never a time. Re-run when
 * a change is meant to move an own point's lateness, or to take in the rows `prove` adds (until then a new row is
 * held to its entry's documented limits alone), then commit.
 */
fun main(args: Array<String>) {
    fun option(name: String): String? = args.indexOf(name).takeIf { it >= 0 }?.let { args.getOrNull(it + 1) }
    val repo = File(option("--repo") ?: fail("--repo is required"))
    val official = File(option("--official") ?: fail("--official is required"))
    val roots = OfficialRoots(official, repo.resolve("tools/timetables/official"))
    val manifest = GateManifest.load(repo.resolve("tools/timetables/official/gate"))
    val worst = OwnPointWorst.measure(roots, manifest)
    val out = repo.resolve(OwnPointWorst.FILE)
    out.writeText(OwnPointWorst.render(worst))
    println("Wrote ${worst.size} own-point rows to ${OwnPointWorst.FILE}")
}

private fun fail(problem: String): Nothing {
    System.err.println("generateOwnPointWorst: $problem")
    exitProcess(2)
}

object OwnPointWorst {
    const val FILE = "tools/timetables/official/own-points-worst.tsv"

    val GROUPS = listOf("sa-ummalqura", "kz-qmdb")

    /** The events in the file's order. */
    val EVENTS = listOf("fajr", "sunrise", "dhuhr", "asrStandard", "asrHanafi", "maghrib", "isha", "endOfEating")

    /** One row of a group file as the file names it: its gate file, table, entry (with its unit) and point. */
    fun key(row: GateRow): String = listOf(
        row.source, row.path, row.entry + (row.unit?.let { "/$it" } ?: ""),
        String.format(Locale.ROOT, "%.6f", row.lat), String.format(Locale.ROOT, "%.6f", row.lon),
    ).joinToString("\t")

    fun rows(manifest: GateManifest): List<GateRow> = manifest.only(groups = GROUPS.toSet()).rows

    /** Each row's worst lateness per event, every row on its own. */
    fun measure(roots: OfficialRoots, manifest: GateManifest, threads: Int = 4): Map<String, Map<String, Int>> {
        val pool = Executors.newFixedThreadPool(threads)
        try {
            return rows(manifest).map { row ->
                pool.submit<Pair<String, Map<String, Int>>> {
                    val s = Gate(roots).evaluate(GateManifest(listOf(row))).entries.values.single()
                    key(row) to s.events.entries.associate { (event, e) -> event.key to e.worst }
                }
            }.map { it.get() }.toMap(LinkedHashMap())
        } finally {
            pool.shutdown()
        }
    }

    fun render(worst: Map<String, Map<String, Int>>): String = buildString {
        append("# GENERATED by `./gradlew -p tools/timetables generateOwnPointWorst` (units/OwnPointWorst.kt): each row of\n")
        append("# sa-ummalqura.tsv and kz-qmdb.tsv, its own worst lateness per event in minutes ('-' where it reads none).\n")
        append("# CityUnitsTest holds every row to these (the review of 10 Oct 2026). Minutes, paths and points only.\n")
        append((listOf("gate", "path", "entry", "lat", "lon") + EVENTS).joinToString("\t")).append('\n')
        for ((key, events) in worst) {
            append(key)
            for (e in EVENTS) append('\t').append(events[e]?.toString() ?: "-")
            append('\n')
        }
    }

    fun read(file: File): Map<String, Map<String, Int>> = file.readLines()
        .filter { it.isNotBlank() && !it.startsWith("#") && !it.startsWith("gate\t") }
        .associate { line ->
            val cells = line.split('\t')
            cells.take(5).joinToString("\t") to EVENTS.indices.mapNotNull { i ->
                cells[5 + i].toIntOrNull()?.let { EVENTS[i] to it }
            }.toMap()
        }
}
