package world.taqwa.app.prayer

/**
 * The country a time zone belongs to, for a stored location that has no country code (spec §8:
 * old installs): generated from the bundled `files/cities.csv`, each IANA zone named there mapped
 * to the country most of its cities are in (356 zones). A zone the list does not name gives
 * null, and the engine then follows its safe default until the Prayer screen backfills the
 * country from the nearest city. `ZoneCountriesTest` (Android host) checks it against the
 * list.
 */
object ZoneCountries {

    /** The ISO 3166-1 alpha-2 code of [zoneId]'s country, or null when the city list has no such zone. */
    fun of(zoneId: String): String? = byZone[zoneId]

    private val byZone: Map<String, String> by lazy {
        buildMap {
            fun zone(countryCode: String, vararg zones: String) = zones.forEach { put(it, countryCode) }
            zone("AD", "Europe/Andorra")
            zone("AE", "Asia/Dubai")
            zone("AF", "Asia/Kabul")
            zone("AG", "America/Antigua")
            zone("AI", "America/Anguilla")
            zone("AL", "Europe/Tirane")
            zone("AM", "Asia/Yerevan")
            zone("AO", "Africa/Luanda")
            zone("AR", "America/Argentina/Buenos_Aires", "America/Argentina/Catamarca", "America/Argentina/Cordoba",
                "America/Argentina/Jujuy", "America/Argentina/La_Rioja", "America/Argentina/Mendoza",
                "America/Argentina/Rio_Gallegos", "America/Argentina/Salta", "America/Argentina/San_Juan",
                "America/Argentina/San_Luis", "America/Argentina/Tucuman", "America/Argentina/Ushuaia")
            zone("AS", "Pacific/Pago_Pago")
            zone("AT", "Europe/Vienna")
            zone("AU", "Australia/Adelaide", "Australia/Brisbane", "Australia/Broken_Hill", "Australia/Darwin",
                "Australia/Hobart", "Australia/Melbourne", "Australia/Perth", "Australia/Sydney")
            zone("AW", "America/Aruba")
            zone("AX", "Europe/Mariehamn")
            zone("AZ", "Asia/Baku")
            zone("BA", "Europe/Sarajevo")
            zone("BB", "America/Barbados")
            zone("BD", "Asia/Dhaka")
            zone("BE", "Europe/Brussels")
            zone("BF", "Africa/Ouagadougou")
            zone("BG", "Europe/Sofia")
            zone("BH", "Asia/Bahrain")
            zone("BI", "Africa/Bujumbura")
            zone("BJ", "Africa/Porto-Novo")
            zone("BL", "America/St_Barthelemy")
            zone("BM", "Atlantic/Bermuda")
            zone("BN", "Asia/Brunei")
            zone("BO", "America/La_Paz")
            zone("BQ", "America/Kralendijk")
            zone("BR", "America/Araguaina", "America/Bahia", "America/Belem", "America/Boa_Vista",
                "America/Campo_Grande", "America/Cuiaba", "America/Eirunepe", "America/Fortaleza", "America/Maceio",
                "America/Manaus", "America/Porto_Velho", "America/Recife", "America/Rio_Branco", "America/Santarem",
                "America/Sao_Paulo")
            zone("BS", "America/Nassau")
            zone("BT", "Asia/Thimphu")
            zone("BW", "Africa/Gaborone")
            zone("BY", "Europe/Minsk")
            zone("BZ", "America/Belize")
            zone("CA", "America/Dawson_Creek", "America/Edmonton", "America/Glace_Bay", "America/Halifax",
                "America/Moncton", "America/Regina", "America/St_Johns", "America/Swift_Current", "America/Toronto",
                "America/Vancouver", "America/Whitehorse", "America/Winnipeg")
            zone("CC", "Indian/Cocos")
            zone("CD", "Africa/Kinshasa", "Africa/Lubumbashi")
            zone("CF", "Africa/Bangui")
            zone("CG", "Africa/Brazzaville")
            zone("CH", "Europe/Zurich")
            zone("CI", "Africa/Abidjan")
            zone("CK", "Pacific/Rarotonga")
            zone("CL", "America/Coyhaique", "America/Punta_Arenas", "America/Santiago")
            zone("CM", "Africa/Douala")
            zone("CN", "Asia/Shanghai", "Asia/Urumqi")
            zone("CO", "America/Bogota")
            zone("CR", "America/Costa_Rica")
            zone("CU", "America/Havana")
            zone("CV", "Atlantic/Cape_Verde")
            zone("CW", "America/Curacao")
            zone("CX", "Indian/Christmas")
            zone("CY", "Asia/Famagusta", "Asia/Nicosia")
            zone("CZ", "Europe/Prague")
            zone("DE", "Europe/Berlin")
            zone("DJ", "Africa/Djibouti")
            zone("DK", "Europe/Copenhagen")
            zone("DM", "America/Dominica")
            zone("DO", "America/Santo_Domingo")
            zone("DZ", "Africa/Algiers")
            zone("EC", "America/Guayaquil")
            zone("EE", "Europe/Tallinn")
            zone("EG", "Africa/Cairo")
            zone("EH", "Africa/El_Aaiun")
            zone("ER", "Africa/Asmara")
            zone("ES", "Africa/Ceuta", "Atlantic/Canary", "Europe/Madrid")
            zone("ET", "Africa/Addis_Ababa")
            zone("FI", "Europe/Helsinki")
            zone("FJ", "Pacific/Fiji")
            zone("FK", "Atlantic/Stanley")
            zone("FM", "Pacific/Pohnpei")
            zone("FO", "Atlantic/Faroe")
            zone("FR", "Europe/Paris")
            zone("GA", "Africa/Libreville")
            zone("GB", "Europe/London")
            zone("GD", "America/Grenada")
            zone("GE", "Asia/Tbilisi")
            zone("GF", "America/Cayenne")
            zone("GG", "Europe/Guernsey")
            zone("GH", "Africa/Accra")
            zone("GI", "Europe/Gibraltar")
            zone("GL", "America/Nuuk")
            zone("GM", "Africa/Banjul")
            zone("GN", "Africa/Conakry")
            zone("GP", "America/Guadeloupe")
            zone("GQ", "Africa/Malabo")
            zone("GR", "Europe/Athens")
            zone("GS", "Atlantic/South_Georgia")
            zone("GT", "America/Guatemala")
            zone("GU", "Pacific/Guam")
            zone("GW", "Africa/Bissau")
            zone("GY", "America/Guyana")
            zone("HK", "Asia/Hong_Kong")
            zone("HN", "America/Tegucigalpa")
            zone("HR", "Europe/Zagreb")
            zone("HT", "America/Port-au-Prince")
            zone("HU", "Europe/Budapest")
            zone("ID", "Asia/Jakarta", "Asia/Jayapura", "Asia/Makassar", "Asia/Pontianak")
            zone("IE", "Europe/Dublin")
            zone("IL", "Asia/Jerusalem")
            zone("IM", "Europe/Isle_of_Man")
            zone("IN", "Asia/Kolkata")
            zone("IQ", "Asia/Baghdad")
            zone("IR", "Asia/Tehran")
            zone("IS", "Atlantic/Reykjavik")
            zone("IT", "Europe/Rome")
            zone("JE", "Europe/Jersey")
            zone("JM", "America/Jamaica")
            zone("JO", "Asia/Amman")
            zone("JP", "Asia/Tokyo")
            zone("KE", "Africa/Nairobi")
            zone("KG", "Asia/Bishkek")
            zone("KH", "Asia/Phnom_Penh")
            zone("KI", "Pacific/Tarawa")
            zone("KM", "Indian/Comoro")
            zone("KN", "America/St_Kitts")
            zone("KP", "Asia/Pyongyang")
            zone("KR", "Asia/Seoul")
            zone("KW", "Asia/Kuwait")
            zone("KY", "America/Cayman")
            zone("KZ", "Asia/Almaty", "Asia/Aqtau", "Asia/Aqtobe", "Asia/Atyrau", "Asia/Oral", "Asia/Qostanay",
                "Asia/Qyzylorda")
            zone("LA", "Asia/Vientiane")
            zone("LB", "Asia/Beirut")
            zone("LC", "America/St_Lucia")
            zone("LI", "Europe/Vaduz")
            zone("LK", "Asia/Colombo")
            zone("LR", "Africa/Monrovia")
            zone("LS", "Africa/Maseru")
            zone("LT", "Europe/Vilnius")
            zone("LU", "Europe/Luxembourg")
            zone("LV", "Europe/Riga")
            zone("LY", "Africa/Tripoli")
            zone("MA", "Africa/Casablanca")
            zone("MC", "Europe/Monaco")
            zone("MD", "Europe/Chisinau")
            zone("ME", "Europe/Podgorica")
            zone("MF", "America/Marigot")
            zone("MG", "Indian/Antananarivo")
            zone("MH", "Pacific/Majuro")
            zone("MK", "Europe/Skopje")
            zone("ML", "Africa/Bamako")
            zone("MM", "Asia/Yangon")
            zone("MN", "Asia/Hovd", "Asia/Ulaanbaatar")
            zone("MO", "Asia/Macau")
            zone("MP", "Pacific/Saipan")
            zone("MQ", "America/Martinique")
            zone("MR", "Africa/Nouakchott")
            zone("MS", "America/Montserrat")
            zone("MT", "Europe/Malta")
            zone("MU", "Indian/Mauritius")
            zone("MV", "Indian/Maldives")
            zone("MW", "Africa/Blantyre")
            zone("MX", "America/Bahia_Banderas", "America/Cancun", "America/Chihuahua", "America/Ciudad_Juarez",
                "America/Hermosillo", "America/Matamoros", "America/Mazatlan", "America/Merida", "America/Mexico_City",
                "America/Monterrey", "America/Ojinaga", "America/Tijuana")
            zone("MY", "Asia/Kuala_Lumpur", "Asia/Kuching")
            zone("MZ", "Africa/Maputo")
            zone("NA", "Africa/Windhoek")
            zone("NC", "Pacific/Noumea")
            zone("NE", "Africa/Niamey")
            zone("NF", "Pacific/Norfolk")
            zone("NG", "Africa/Lagos")
            zone("NI", "America/Managua")
            zone("NL", "Europe/Amsterdam")
            zone("NO", "Europe/Oslo")
            zone("NP", "Asia/Kathmandu")
            zone("NR", "Pacific/Nauru")
            zone("NU", "Pacific/Niue")
            zone("NZ", "Pacific/Auckland")
            zone("OM", "Asia/Muscat")
            zone("PA", "America/Panama")
            zone("PE", "America/Lima")
            zone("PF", "Pacific/Tahiti")
            zone("PG", "Pacific/Bougainville", "Pacific/Port_Moresby")
            zone("PH", "Asia/Manila")
            zone("PK", "Asia/Karachi")
            zone("PL", "Europe/Warsaw")
            zone("PM", "America/Miquelon")
            zone("PN", "Pacific/Pitcairn")
            zone("PR", "America/Puerto_Rico")
            zone("PS", "Asia/Gaza", "Asia/Hebron")
            zone("PT", "Atlantic/Azores", "Atlantic/Madeira", "Europe/Lisbon")
            zone("PW", "Pacific/Palau")
            zone("PY", "America/Asuncion")
            zone("QA", "Asia/Qatar")
            zone("RE", "Indian/Reunion")
            zone("RO", "Europe/Bucharest")
            zone("RS", "Europe/Belgrade")
            zone("RU", "Asia/Anadyr", "Asia/Barnaul", "Asia/Chita", "Asia/Irkutsk", "Asia/Kamchatka",
                "Asia/Krasnoyarsk", "Asia/Magadan", "Asia/Novokuznetsk", "Asia/Novosibirsk", "Asia/Omsk",
                "Asia/Sakhalin", "Asia/Tomsk", "Asia/Vladivostok", "Asia/Yakutsk", "Asia/Yekaterinburg",
                "Europe/Astrakhan", "Europe/Kaliningrad", "Europe/Kirov", "Europe/Moscow", "Europe/Samara",
                "Europe/Saratov", "Europe/Ulyanovsk", "Europe/Volgograd")
            zone("RW", "Africa/Kigali")
            zone("SA", "Asia/Riyadh")
            zone("SB", "Pacific/Guadalcanal")
            zone("SC", "Indian/Mahe")
            zone("SD", "Africa/Khartoum")
            zone("SE", "Europe/Stockholm")
            zone("SG", "Asia/Singapore")
            zone("SH", "Atlantic/St_Helena")
            zone("SI", "Europe/Ljubljana")
            zone("SJ", "Arctic/Longyearbyen")
            zone("SK", "Europe/Bratislava")
            zone("SL", "Africa/Freetown")
            zone("SM", "Europe/San_Marino")
            zone("SN", "Africa/Dakar")
            zone("SO", "Africa/Mogadishu")
            zone("SR", "America/Paramaribo")
            zone("SS", "Africa/Juba")
            zone("ST", "Africa/Sao_Tome")
            zone("SV", "America/El_Salvador")
            zone("SX", "America/Lower_Princes")
            zone("SY", "Asia/Damascus")
            zone("SZ", "Africa/Mbabane")
            zone("TC", "America/Grand_Turk")
            zone("TD", "Africa/Ndjamena")
            zone("TF", "Indian/Kerguelen")
            zone("TG", "Africa/Lome")
            zone("TH", "Asia/Bangkok")
            zone("TJ", "Asia/Dushanbe")
            zone("TL", "Asia/Dili")
            zone("TM", "Asia/Ashgabat")
            zone("TN", "Africa/Tunis")
            zone("TO", "Pacific/Tongatapu")
            zone("TR", "Europe/Istanbul")
            zone("TT", "America/Port_of_Spain")
            zone("TV", "Pacific/Funafuti")
            zone("TW", "Asia/Taipei")
            zone("TZ", "Africa/Dar_es_Salaam")
            zone("UA", "Europe/Kyiv", "Europe/Simferopol")
            zone("UG", "Africa/Kampala")
            zone("US", "America/Anchorage", "America/Boise", "America/Chicago", "America/Denver", "America/Detroit",
                "America/Indiana/Indianapolis", "America/Indiana/Vincennes", "America/Juneau",
                "America/Kentucky/Louisville", "America/Los_Angeles", "America/New_York",
                "America/North_Dakota/New_Salem", "America/Phoenix", "Pacific/Honolulu")
            zone("UY", "America/Montevideo")
            zone("UZ", "Asia/Samarkand", "Asia/Tashkent")
            zone("VA", "Europe/Vatican")
            zone("VC", "America/St_Vincent")
            zone("VE", "America/Caracas")
            zone("VG", "America/Tortola")
            zone("VI", "America/St_Thomas")
            zone("VN", "Asia/Ho_Chi_Minh")
            zone("VU", "Pacific/Efate")
            zone("WF", "Pacific/Wallis")
            zone("WS", "Pacific/Apia")
            zone("YE", "Asia/Aden")
            zone("YT", "Indian/Mayotte")
            zone("ZA", "Africa/Johannesburg")
            zone("ZM", "Africa/Lusaka")
            zone("ZW", "Africa/Harare")
        }
    }
}
