package world.taqwa.app.feature.quran

import world.taqwa.app.quran.LineType
import world.taqwa.app.quran.LineWord
import world.taqwa.app.quran.MushafLine
import world.taqwa.app.quran.MushafPage

/**
 * Pages 1, 2 and 3 of the Madinah Mushaf, copied verbatim out of the bundled
 * `quran.db` (`page`, `page_line` and `line_word`) by `tools/dump-mushaf-fixtures.py` rather than
 * typed: the global rule is that Quran text is never retyped, and that holds for test fixtures too.
 * Regenerate, never edit.
 *
 * Between them these three pages carry every shape [MushafViewModel] and [MushafPageView] have to
 * handle: page 1 is Al-Faatiha's short, vertically centred page with a `SURAH` band and a line
 * that ends a surah; page 2 adds a `BASMALA` line; page 3 is an ordinary 15-line text page whose
 * first line starts at 2:6 - which is what the reader has to return to when the mode toggle goes
 * back to translation.
 */

internal val MUSHAF_PAGE_1 = MushafPage(1, 1, 1, 1, listOf(
    MushafLine(
        line = 1, type = LineType.SURAH, surah = 1,
        text = null,
        firstSurah = null, firstAyah = null,
        lastSurah = null, lastAyah = null,
        endsSurah = false,
        words = emptyList(),
    ),
    MushafLine(
        line = 2, type = LineType.TEXT, surah = null,
        text = "بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ\u00a0١",
        firstSurah = 1, firstAyah = 1,
        lastSurah = 1, lastAyah = 1,
        endsSurah = false,
        words = listOf(
            LineWord(1, 1, 1, 1, "بِسْمِ"),
            LineWord(2, 1, 1, 2, "ٱللَّهِ"),
            LineWord(3, 1, 1, 3, "ٱلرَّحْمَـٰنِ"),
            LineWord(4, 1, 1, 4, "ٱلرَّحِيمِ\u00a0١"),
        ),
    ),
    MushafLine(
        line = 3, type = LineType.TEXT, surah = null,
        text = "ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَـٰلَمِينَ\u00a0٢",
        firstSurah = 1, firstAyah = 2,
        lastSurah = 1, lastAyah = 2,
        endsSurah = false,
        words = listOf(
            LineWord(1, 1, 2, 1, "ٱلْحَمْدُ"),
            LineWord(2, 1, 2, 2, "لِلَّهِ"),
            LineWord(3, 1, 2, 3, "رَبِّ"),
            LineWord(4, 1, 2, 4, "ٱلْعَـٰلَمِينَ\u00a0٢"),
        ),
    ),
    MushafLine(
        line = 4, type = LineType.TEXT, surah = null,
        text = "ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ\u00a0٣ مَـٰلِكِ يَوْمِ ٱلدِّينِ\u00a0٤",
        firstSurah = 1, firstAyah = 3,
        lastSurah = 1, lastAyah = 4,
        endsSurah = false,
        words = listOf(
            LineWord(1, 1, 3, 1, "ٱلرَّحْمَـٰنِ"),
            LineWord(2, 1, 3, 2, "ٱلرَّحِيمِ\u00a0٣"),
            LineWord(3, 1, 4, 1, "مَـٰلِكِ"),
            LineWord(4, 1, 4, 2, "يَوْمِ"),
            LineWord(5, 1, 4, 3, "ٱلدِّينِ\u00a0٤"),
        ),
    ),
    MushafLine(
        line = 5, type = LineType.TEXT, surah = null,
        text = "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ\u00a0٥ ٱهْدِنَا",
        firstSurah = 1, firstAyah = 5,
        lastSurah = 1, lastAyah = 6,
        endsSurah = false,
        words = listOf(
            LineWord(1, 1, 5, 1, "إِيَّاكَ"),
            LineWord(2, 1, 5, 2, "نَعْبُدُ"),
            LineWord(3, 1, 5, 3, "وَإِيَّاكَ"),
            LineWord(4, 1, 5, 4, "نَسْتَعِينُ\u00a0٥"),
            LineWord(5, 1, 6, 1, "ٱهْدِنَا"),
        ),
    ),
    MushafLine(
        line = 6, type = LineType.TEXT, surah = null,
        text = "ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ\u00a0٦ صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ",
        firstSurah = 1, firstAyah = 6,
        lastSurah = 1, lastAyah = 7,
        endsSurah = false,
        words = listOf(
            LineWord(1, 1, 6, 2, "ٱلصِّرَٰطَ"),
            LineWord(2, 1, 6, 3, "ٱلْمُسْتَقِيمَ\u00a0٦"),
            LineWord(3, 1, 7, 1, "صِرَٰطَ"),
            LineWord(4, 1, 7, 2, "ٱلَّذِينَ"),
            LineWord(5, 1, 7, 3, "أَنْعَمْتَ"),
        ),
    ),
    MushafLine(
        line = 7, type = LineType.TEXT, surah = null,
        text = "عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ",
        firstSurah = 1, firstAyah = 7,
        lastSurah = 1, lastAyah = 7,
        endsSurah = false,
        words = listOf(
            LineWord(1, 1, 7, 4, "عَلَيْهِمْ"),
            LineWord(2, 1, 7, 5, "غَيْرِ"),
            LineWord(3, 1, 7, 6, "ٱلْمَغْضُوبِ"),
            LineWord(4, 1, 7, 7, "عَلَيْهِمْ"),
        ),
    ),
    MushafLine(
        line = 8, type = LineType.TEXT, surah = null,
        text = "وَلَا ٱلضَّآلِّينَ\u00a0٧",
        firstSurah = 1, firstAyah = 7,
        lastSurah = 1, lastAyah = 7,
        endsSurah = true,
        words = listOf(
            LineWord(1, 1, 7, 8, "وَلَا"),
            LineWord(2, 1, 7, 9, "ٱلضَّآلِّينَ\u00a0٧"),
        ),
    ),
))

internal val MUSHAF_PAGE_2 = MushafPage(2, 2, 1, 1, listOf(
    MushafLine(
        line = 1, type = LineType.SURAH, surah = 2,
        text = null,
        firstSurah = null, firstAyah = null,
        lastSurah = null, lastAyah = null,
        endsSurah = false,
        words = emptyList(),
    ),
    MushafLine(
        line = 2, type = LineType.BASMALA, surah = null,
        text = null,
        firstSurah = null, firstAyah = null,
        lastSurah = null, lastAyah = null,
        endsSurah = false,
        words = emptyList(),
    ),
    MushafLine(
        line = 3, type = LineType.TEXT, surah = null,
        text = "الٓمٓ\u00a0١ ذَٰلِكَ ٱلْكِتَـٰبُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًى",
        firstSurah = 2, firstAyah = 1,
        lastSurah = 2, lastAyah = 2,
        endsSurah = false,
        words = listOf(
            LineWord(1, 2, 1, 1, "الٓمٓ\u00a0١"),
            LineWord(2, 2, 2, 1, "ذَٰلِكَ"),
            LineWord(3, 2, 2, 2, "ٱلْكِتَـٰبُ"),
            LineWord(4, 2, 2, 3, "لَا"),
            LineWord(5, 2, 2, 4, "رَيْبَ ۛ"),
            LineWord(6, 2, 2, 5, "فِيهِ ۛ"),
            LineWord(7, 2, 2, 6, "هُدًى"),
        ),
    ),
    MushafLine(
        line = 4, type = LineType.TEXT, surah = null,
        text = "لِّلْمُتَّقِينَ\u00a0٢ ٱلَّذِينَ يُؤْمِنُونَ بِٱلْغَيْبِ وَيُقِيمُونَ ٱلصَّلَوٰةَ",
        firstSurah = 2, firstAyah = 2,
        lastSurah = 2, lastAyah = 3,
        endsSurah = false,
        words = listOf(
            LineWord(1, 2, 2, 7, "لِّلْمُتَّقِينَ\u00a0٢"),
            LineWord(2, 2, 3, 1, "ٱلَّذِينَ"),
            LineWord(3, 2, 3, 2, "يُؤْمِنُونَ"),
            LineWord(4, 2, 3, 3, "بِٱلْغَيْبِ"),
            LineWord(5, 2, 3, 4, "وَيُقِيمُونَ"),
            LineWord(6, 2, 3, 5, "ٱلصَّلَوٰةَ"),
        ),
    ),
    MushafLine(
        line = 5, type = LineType.TEXT, surah = null,
        text = "وَمِمَّا رَزَقْنَـٰهُمْ يُنفِقُونَ\u00a0٣ وَٱلَّذِينَ يُؤْمِنُونَ بِمَآ أُنزِلَ",
        firstSurah = 2, firstAyah = 3,
        lastSurah = 2, lastAyah = 4,
        endsSurah = false,
        words = listOf(
            LineWord(1, 2, 3, 6, "وَمِمَّا"),
            LineWord(2, 2, 3, 7, "رَزَقْنَـٰهُمْ"),
            LineWord(3, 2, 3, 8, "يُنفِقُونَ\u00a0٣"),
            LineWord(4, 2, 4, 1, "وَٱلَّذِينَ"),
            LineWord(5, 2, 4, 2, "يُؤْمِنُونَ"),
            LineWord(6, 2, 4, 3, "بِمَآ"),
            LineWord(7, 2, 4, 4, "أُنزِلَ"),
        ),
    ),
    MushafLine(
        line = 6, type = LineType.TEXT, surah = null,
        text = "إِلَيْكَ وَمَآ أُنزِلَ مِن قَبْلِكَ وَبِٱلْـَٔاخِرَةِ هُمْ يُوقِنُونَ\u00a0٤",
        firstSurah = 2, firstAyah = 4,
        lastSurah = 2, lastAyah = 4,
        endsSurah = false,
        words = listOf(
            LineWord(1, 2, 4, 5, "إِلَيْكَ"),
            LineWord(2, 2, 4, 6, "وَمَآ"),
            LineWord(3, 2, 4, 7, "أُنزِلَ"),
            LineWord(4, 2, 4, 8, "مِن"),
            LineWord(5, 2, 4, 9, "قَبْلِكَ"),
            LineWord(6, 2, 4, 10, "وَبِٱلْـَٔاخِرَةِ"),
            LineWord(7, 2, 4, 11, "هُمْ"),
            LineWord(8, 2, 4, 12, "يُوقِنُونَ\u00a0٤"),
        ),
    ),
    MushafLine(
        line = 7, type = LineType.TEXT, surah = null,
        text = "أُوْلَـٰٓئِكَ عَلَىٰ هُدًى مِّن رَّبِّهِمْ ۖ وَأُوْلَـٰٓئِكَ",
        firstSurah = 2, firstAyah = 5,
        lastSurah = 2, lastAyah = 5,
        endsSurah = false,
        words = listOf(
            LineWord(1, 2, 5, 1, "أُوْلَـٰٓئِكَ"),
            LineWord(2, 2, 5, 2, "عَلَىٰ"),
            LineWord(3, 2, 5, 3, "هُدًى"),
            LineWord(4, 2, 5, 4, "مِّن"),
            LineWord(5, 2, 5, 5, "رَّبِّهِمْ ۖ"),
            LineWord(6, 2, 5, 6, "وَأُوْلَـٰٓئِكَ"),
        ),
    ),
    MushafLine(
        line = 8, type = LineType.TEXT, surah = null,
        text = "هُمُ ٱلْمُفْلِحُونَ\u00a0٥",
        firstSurah = 2, firstAyah = 5,
        lastSurah = 2, lastAyah = 5,
        endsSurah = false,
        words = listOf(
            LineWord(1, 2, 5, 7, "هُمُ"),
            LineWord(2, 2, 5, 8, "ٱلْمُفْلِحُونَ\u00a0٥"),
        ),
    ),
))

internal val MUSHAF_PAGE_3 = MushafPage(3, 2, 6, 1, listOf(
    MushafLine(
        line = 1, type = LineType.TEXT, surah = null,
        text = "إِنَّ ٱلَّذِينَ كَفَرُواْ سَوَآءٌ عَلَيْهِمْ ءَأَنذَرْتَهُمْ أَمْ لَمْ تُنذِرْهُمْ",
        firstSurah = 2, firstAyah = 6,
        lastSurah = 2, lastAyah = 6,
        endsSurah = false,
        words = listOf(
            LineWord(1, 2, 6, 1, "إِنَّ"),
            LineWord(2, 2, 6, 2, "ٱلَّذِينَ"),
            LineWord(3, 2, 6, 3, "كَفَرُواْ"),
            LineWord(4, 2, 6, 4, "سَوَآءٌ"),
            LineWord(5, 2, 6, 5, "عَلَيْهِمْ"),
            LineWord(6, 2, 6, 6, "ءَأَنذَرْتَهُمْ"),
            LineWord(7, 2, 6, 7, "أَمْ"),
            LineWord(8, 2, 6, 8, "لَمْ"),
            LineWord(9, 2, 6, 9, "تُنذِرْهُمْ"),
        ),
    ),
    MushafLine(
        line = 2, type = LineType.TEXT, surah = null,
        text = "لَا يُؤْمِنُونَ\u00a0٦ خَتَمَ ٱللَّهُ عَلَىٰ قُلُوبِهِمْ وَعَلَىٰ سَمْعِهِمْ ۖ وَعَلَىٰٓ",
        firstSurah = 2, firstAyah = 6,
        lastSurah = 2, lastAyah = 7,
        endsSurah = false,
        words = listOf(
            LineWord(1, 2, 6, 10, "لَا"),
            LineWord(2, 2, 6, 11, "يُؤْمِنُونَ\u00a0٦"),
            LineWord(3, 2, 7, 1, "خَتَمَ"),
            LineWord(4, 2, 7, 2, "ٱللَّهُ"),
            LineWord(5, 2, 7, 3, "عَلَىٰ"),
            LineWord(6, 2, 7, 4, "قُلُوبِهِمْ"),
            LineWord(7, 2, 7, 5, "وَعَلَىٰ"),
            LineWord(8, 2, 7, 6, "سَمْعِهِمْ ۖ"),
            LineWord(9, 2, 7, 7, "وَعَلَىٰٓ"),
        ),
    ),
    MushafLine(
        line = 3, type = LineType.TEXT, surah = null,
        text = "أَبْصَـٰرِهِمْ غِشَـٰوَةٌ ۖ وَلَهُمْ عَذَابٌ عَظِيمٌ\u00a0٧ وَمِنَ ٱلنَّاسِ",
        firstSurah = 2, firstAyah = 7,
        lastSurah = 2, lastAyah = 8,
        endsSurah = false,
        words = listOf(
            LineWord(1, 2, 7, 8, "أَبْصَـٰرِهِمْ"),
            LineWord(2, 2, 7, 9, "غِشَـٰوَةٌ ۖ"),
            LineWord(3, 2, 7, 10, "وَلَهُمْ"),
            LineWord(4, 2, 7, 11, "عَذَابٌ"),
            LineWord(5, 2, 7, 12, "عَظِيمٌ\u00a0٧"),
            LineWord(6, 2, 8, 1, "وَمِنَ"),
            LineWord(7, 2, 8, 2, "ٱلنَّاسِ"),
        ),
    ),
    MushafLine(
        line = 4, type = LineType.TEXT, surah = null,
        text = "مَن يَقُولُ ءَامَنَّا بِٱللَّهِ وَبِٱلْيَوْمِ ٱلْـَٔاخِرِ وَمَا هُم بِمُؤْمِنِينَ\u00a0٨",
        firstSurah = 2, firstAyah = 8,
        lastSurah = 2, lastAyah = 8,
        endsSurah = false,
        words = listOf(
            LineWord(1, 2, 8, 3, "مَن"),
            LineWord(2, 2, 8, 4, "يَقُولُ"),
            LineWord(3, 2, 8, 5, "ءَامَنَّا"),
            LineWord(4, 2, 8, 6, "بِٱللَّهِ"),
            LineWord(5, 2, 8, 7, "وَبِٱلْيَوْمِ"),
            LineWord(6, 2, 8, 8, "ٱلْـَٔاخِرِ"),
            LineWord(7, 2, 8, 9, "وَمَا"),
            LineWord(8, 2, 8, 10, "هُم"),
            LineWord(9, 2, 8, 11, "بِمُؤْمِنِينَ\u00a0٨"),
        ),
    ),
    MushafLine(
        line = 5, type = LineType.TEXT, surah = null,
        text = "يُخَـٰدِعُونَ ٱللَّهَ وَٱلَّذِينَ ءَامَنُواْ وَمَا يَخْدَعُونَ إِلَّآ أَنفُسَهُمْ",
        firstSurah = 2, firstAyah = 9,
        lastSurah = 2, lastAyah = 9,
        endsSurah = false,
        words = listOf(
            LineWord(1, 2, 9, 1, "يُخَـٰدِعُونَ"),
            LineWord(2, 2, 9, 2, "ٱللَّهَ"),
            LineWord(3, 2, 9, 3, "وَٱلَّذِينَ"),
            LineWord(4, 2, 9, 4, "ءَامَنُواْ"),
            LineWord(5, 2, 9, 5, "وَمَا"),
            LineWord(6, 2, 9, 6, "يَخْدَعُونَ"),
            LineWord(7, 2, 9, 7, "إِلَّآ"),
            LineWord(8, 2, 9, 8, "أَنفُسَهُمْ"),
        ),
    ),
    MushafLine(
        line = 6, type = LineType.TEXT, surah = null,
        text = "وَمَا يَشْعُرُونَ\u00a0٩ فِى قُلُوبِهِم مَّرَضٌ فَزَادَهُمُ ٱللَّهُ مَرَضًا ۖ",
        firstSurah = 2, firstAyah = 9,
        lastSurah = 2, lastAyah = 10,
        endsSurah = false,
        words = listOf(
            LineWord(1, 2, 9, 9, "وَمَا"),
            LineWord(2, 2, 9, 10, "يَشْعُرُونَ\u00a0٩"),
            LineWord(3, 2, 10, 1, "فِى"),
            LineWord(4, 2, 10, 2, "قُلُوبِهِم"),
            LineWord(5, 2, 10, 3, "مَّرَضٌ"),
            LineWord(6, 2, 10, 4, "فَزَادَهُمُ"),
            LineWord(7, 2, 10, 5, "ٱللَّهُ"),
            LineWord(8, 2, 10, 6, "مَرَضًا ۖ"),
        ),
    ),
    MushafLine(
        line = 7, type = LineType.TEXT, surah = null,
        text = "وَلَهُمْ عَذَابٌ أَلِيمٌۢ بِمَا كَانُواْ يَكْذِبُونَ\u00a0١٠ وَإِذَا قِيلَ لَهُمْ",
        firstSurah = 2, firstAyah = 10,
        lastSurah = 2, lastAyah = 11,
        endsSurah = false,
        words = listOf(
            LineWord(1, 2, 10, 7, "وَلَهُمْ"),
            LineWord(2, 2, 10, 8, "عَذَابٌ"),
            LineWord(3, 2, 10, 9, "أَلِيمٌۢ"),
            LineWord(4, 2, 10, 10, "بِمَا"),
            LineWord(5, 2, 10, 11, "كَانُواْ"),
            LineWord(6, 2, 10, 12, "يَكْذِبُونَ\u00a0١٠"),
            LineWord(7, 2, 11, 1, "وَإِذَا"),
            LineWord(8, 2, 11, 2, "قِيلَ"),
            LineWord(9, 2, 11, 3, "لَهُمْ"),
        ),
    ),
    MushafLine(
        line = 8, type = LineType.TEXT, surah = null,
        text = "لَا تُفْسِدُواْ فِى ٱلْأَرْضِ قَالُوٓاْ إِنَّمَا نَحْنُ مُصْلِحُونَ\u00a0١١",
        firstSurah = 2, firstAyah = 11,
        lastSurah = 2, lastAyah = 11,
        endsSurah = false,
        words = listOf(
            LineWord(1, 2, 11, 4, "لَا"),
            LineWord(2, 2, 11, 5, "تُفْسِدُواْ"),
            LineWord(3, 2, 11, 6, "فِى"),
            LineWord(4, 2, 11, 7, "ٱلْأَرْضِ"),
            LineWord(5, 2, 11, 8, "قَالُوٓاْ"),
            LineWord(6, 2, 11, 9, "إِنَّمَا"),
            LineWord(7, 2, 11, 10, "نَحْنُ"),
            LineWord(8, 2, 11, 11, "مُصْلِحُونَ\u00a0١١"),
        ),
    ),
    MushafLine(
        line = 9, type = LineType.TEXT, surah = null,
        text = "أَلَآ إِنَّهُمْ هُمُ ٱلْمُفْسِدُونَ وَلَـٰكِن لَّا يَشْعُرُونَ\u00a0١٢ وَإِذَا قِيلَ",
        firstSurah = 2, firstAyah = 12,
        lastSurah = 2, lastAyah = 13,
        endsSurah = false,
        words = listOf(
            LineWord(1, 2, 12, 1, "أَلَآ"),
            LineWord(2, 2, 12, 2, "إِنَّهُمْ"),
            LineWord(3, 2, 12, 3, "هُمُ"),
            LineWord(4, 2, 12, 4, "ٱلْمُفْسِدُونَ"),
            LineWord(5, 2, 12, 5, "وَلَـٰكِن"),
            LineWord(6, 2, 12, 6, "لَّا"),
            LineWord(7, 2, 12, 7, "يَشْعُرُونَ\u00a0١٢"),
            LineWord(8, 2, 13, 1, "وَإِذَا"),
            LineWord(9, 2, 13, 2, "قِيلَ"),
        ),
    ),
    MushafLine(
        line = 10, type = LineType.TEXT, surah = null,
        text = "لَهُمْ ءَامِنُواْ كَمَآ ءَامَنَ ٱلنَّاسُ قَالُوٓاْ أَنُؤْمِنُ كَمَآ ءَامَنَ ٱلسُّفَهَآءُ ۗ",
        firstSurah = 2, firstAyah = 13,
        lastSurah = 2, lastAyah = 13,
        endsSurah = false,
        words = listOf(
            LineWord(1, 2, 13, 3, "لَهُمْ"),
            LineWord(2, 2, 13, 4, "ءَامِنُواْ"),
            LineWord(3, 2, 13, 5, "كَمَآ"),
            LineWord(4, 2, 13, 6, "ءَامَنَ"),
            LineWord(5, 2, 13, 7, "ٱلنَّاسُ"),
            LineWord(6, 2, 13, 8, "قَالُوٓاْ"),
            LineWord(7, 2, 13, 9, "أَنُؤْمِنُ"),
            LineWord(8, 2, 13, 10, "كَمَآ"),
            LineWord(9, 2, 13, 11, "ءَامَنَ"),
            LineWord(10, 2, 13, 12, "ٱلسُّفَهَآءُ ۗ"),
        ),
    ),
    MushafLine(
        line = 11, type = LineType.TEXT, surah = null,
        text = "أَلَآ إِنَّهُمْ هُمُ ٱلسُّفَهَآءُ وَلَـٰكِن لَّا يَعْلَمُونَ\u00a0١٣ وَإِذَا لَقُواْ",
        firstSurah = 2, firstAyah = 13,
        lastSurah = 2, lastAyah = 14,
        endsSurah = false,
        words = listOf(
            LineWord(1, 2, 13, 13, "أَلَآ"),
            LineWord(2, 2, 13, 14, "إِنَّهُمْ"),
            LineWord(3, 2, 13, 15, "هُمُ"),
            LineWord(4, 2, 13, 16, "ٱلسُّفَهَآءُ"),
            LineWord(5, 2, 13, 17, "وَلَـٰكِن"),
            LineWord(6, 2, 13, 18, "لَّا"),
            LineWord(7, 2, 13, 19, "يَعْلَمُونَ\u00a0١٣"),
            LineWord(8, 2, 14, 1, "وَإِذَا"),
            LineWord(9, 2, 14, 2, "لَقُواْ"),
        ),
    ),
    MushafLine(
        line = 12, type = LineType.TEXT, surah = null,
        text = "ٱلَّذِينَ ءَامَنُواْ قَالُوٓاْ ءَامَنَّا وَإِذَا خَلَوْاْ إِلَىٰ شَيَـٰطِينِهِمْ قَالُوٓاْ إِنَّا",
        firstSurah = 2, firstAyah = 14,
        lastSurah = 2, lastAyah = 14,
        endsSurah = false,
        words = listOf(
            LineWord(1, 2, 14, 3, "ٱلَّذِينَ"),
            LineWord(2, 2, 14, 4, "ءَامَنُواْ"),
            LineWord(3, 2, 14, 5, "قَالُوٓاْ"),
            LineWord(4, 2, 14, 6, "ءَامَنَّا"),
            LineWord(5, 2, 14, 7, "وَإِذَا"),
            LineWord(6, 2, 14, 8, "خَلَوْاْ"),
            LineWord(7, 2, 14, 9, "إِلَىٰ"),
            LineWord(8, 2, 14, 10, "شَيَـٰطِينِهِمْ"),
            LineWord(9, 2, 14, 11, "قَالُوٓاْ"),
            LineWord(10, 2, 14, 12, "إِنَّا"),
        ),
    ),
    MushafLine(
        line = 13, type = LineType.TEXT, surah = null,
        text = "مَعَكُمْ إِنَّمَا نَحْنُ مُسْتَهْزِءُونَ\u00a0١٤ ٱللَّهُ يَسْتَهْزِئُ بِهِمْ وَيَمُدُّهُمْ",
        firstSurah = 2, firstAyah = 14,
        lastSurah = 2, lastAyah = 15,
        endsSurah = false,
        words = listOf(
            LineWord(1, 2, 14, 13, "مَعَكُمْ"),
            LineWord(2, 2, 14, 14, "إِنَّمَا"),
            LineWord(3, 2, 14, 15, "نَحْنُ"),
            LineWord(4, 2, 14, 16, "مُسْتَهْزِءُونَ\u00a0١٤"),
            LineWord(5, 2, 15, 1, "ٱللَّهُ"),
            LineWord(6, 2, 15, 2, "يَسْتَهْزِئُ"),
            LineWord(7, 2, 15, 3, "بِهِمْ"),
            LineWord(8, 2, 15, 4, "وَيَمُدُّهُمْ"),
        ),
    ),
    MushafLine(
        line = 14, type = LineType.TEXT, surah = null,
        text = "فِى طُغْيَـٰنِهِمْ يَعْمَهُونَ\u00a0١٥ أُوْلَـٰٓئِكَ ٱلَّذِينَ ٱشْتَرَوُاْ ٱلضَّلَـٰلَةَ",
        firstSurah = 2, firstAyah = 15,
        lastSurah = 2, lastAyah = 16,
        endsSurah = false,
        words = listOf(
            LineWord(1, 2, 15, 5, "فِى"),
            LineWord(2, 2, 15, 6, "طُغْيَـٰنِهِمْ"),
            LineWord(3, 2, 15, 7, "يَعْمَهُونَ\u00a0١٥"),
            LineWord(4, 2, 16, 1, "أُوْلَـٰٓئِكَ"),
            LineWord(5, 2, 16, 2, "ٱلَّذِينَ"),
            LineWord(6, 2, 16, 3, "ٱشْتَرَوُاْ"),
            LineWord(7, 2, 16, 4, "ٱلضَّلَـٰلَةَ"),
        ),
    ),
    MushafLine(
        line = 15, type = LineType.TEXT, surah = null,
        text = "بِٱلْهُدَىٰ فَمَا رَبِحَت تِّجَـٰرَتُهُمْ وَمَا كَانُواْ مُهْتَدِينَ\u00a0١٦",
        firstSurah = 2, firstAyah = 16,
        lastSurah = 2, lastAyah = 16,
        endsSurah = false,
        words = listOf(
            LineWord(1, 2, 16, 5, "بِٱلْهُدَىٰ"),
            LineWord(2, 2, 16, 6, "فَمَا"),
            LineWord(3, 2, 16, 7, "رَبِحَت"),
            LineWord(4, 2, 16, 8, "تِّجَـٰرَتُهُمْ"),
            LineWord(5, 2, 16, 9, "وَمَا"),
            LineWord(6, 2, 16, 10, "كَانُواْ"),
            LineWord(7, 2, 16, 11, "مُهْتَدِينَ\u00a0١٦"),
        ),
    ),
))
